# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6efb153e2305c94f85dfbd3d29ad4aea0f96d1bf286c63dfafde795b8a861d1b9601eda64a823a843297da62532b0469d719f005b50dc992b2ae30c90352d807

test:
  secret_key_base: 47495e452cab59e0345e375210b989865ae628c98fa5d2ec7f0be03cc636b039be944dbde13993563d2bd6be4c2f064976fd106d05c2c7b7a4b85937ff4ca02f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
